---
name: {{ project_name }}-dev
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    # needed for non-root playwright
    # https://playwright.dev/docs/docker
    ipc: host
    security_opt:
      - seccomp:./docker/seccomp_profile.json
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/workspace:cached
    env_file:
      - {{ project_name }}/.env
    command: watchfiles "celery -A {{ project_name }} worker -l info"
    depends_on:
      - app
      - cache
      - postgres


  postgres:
    image: postgis/postgis:18-3.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: {{ project_name }}
      POSTGRES_USER: {{ project_name }}
      POSTGRES_PASSWORD: {{ project_name }}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
